<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE receta [
<!ELEMENT receta (nombre, ingredientes, elaboracion)>
<!ATTLIST receta
    raciones CDATA #REQUIRED
    dificultad (baja | media | alta) "media">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>
<!ATTLIST ingrediente
    cantidad CDATA #IMPLIED
    unidad CDATA #IMPLIED>
<!ELEMENT elaboracion (#PCDATA)>
]>
<receta raciones="6" dificultad="media">
<nombre>Tortilla</nombre>
<ingredientes>
<ingrediente cantidad="1" unidad="kilogramo">Patata</ingrediente>
<ingrediente cantidad="8" unidad="unidades">Huevo</ingrediente>
<ingrediente cantidad="1" unidad="unidades">Cebolla</ingrediente>
<ingrediente>Aceite de oliva</ingrediente>
<ingrediente>Sal</ingrediente>
</ingredientes>
<elaboracion>
Se pelan las patatas...
</elaboracion>
</receta>
